"""Run with Python 3.12 on Linux; output a hashed runtime lock to stdout."""
import json
from pathlib import Path
import subprocess
import sys
import re
from tempfile import TemporaryDirectory
from urllib.request import urlopen


def main():
    requirements = Path("backend/requirements.txt")
    roots = {line.split("==")[0].split("[")[0].lower(): line.split("==")[0]
             for line in requirements.read_text().splitlines() if "==" in line}
    if "--check" in sys.argv:
        def pins(path):
            return {name.lower().replace("_", "-"): version for name, version in
                    re.findall(r"^([\w-]+)(?:\[[^]]+\])?==([^\s\\]+)", path.read_text(), re.MULTILINE)}
        expected, locked = pins(requirements), pins(Path("backend/requirements.lock"))
        if any(locked.get(name) != version for name, version in expected.items()):
            raise SystemExit("Regenerate backend/requirements.lock after changing requirements.txt")
        print("Runtime lock matches direct dependencies")
        return
    with TemporaryDirectory() as directory:
        report = Path(directory) / "report.json"
        subprocess.run([sys.executable, "-m", "pip", "install", "--dry-run", "--ignore-installed",
                        "--report", str(report), "-r", str(requirements)], check=True, stdout=subprocess.DEVNULL)
        packages = json.loads(report.read_text())["install"]
    print("# Generated by tools/lock_requirements.py on Linux / Python 3.12. Do not edit manually.")
    for package in sorted(packages, key=lambda item: item["metadata"]["name"].lower()):
        name, version = package["metadata"]["name"], package["metadata"]["version"]
        with urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=15) as response:
            hashes = sorted({item["digests"]["sha256"] for item in json.load(response)["urls"]})
        if not hashes:
            raise RuntimeError("Missing distribution hashes")
        print(f"{roots.get(name.lower(), name)}=={version} \\")
        for index, digest in enumerate(hashes):
            print("    --hash=sha256:" + digest + (" \\" if index < len(hashes) - 1 else ""))


if __name__ == "__main__":
    main()
